# Generated by Django 4.2.16 on 2024-12-04 14:58

from django.db import migrations

def add_fish_and_fishing_types(apps, schema_editor):
    TypeOfFish = apps.get_model('profiles', 'TypeOfFish')
    TypeOfFishing = apps.get_model('profiles', 'TypeOfFishing')

    fish_choices = [
        'Bass', 'Barbel', 'Bream', 'Brown Trout', 'Catfish', 'Chub', 
        'Common Carp', 'Crucian Carp', 'Dace', 'Eel', 'Ghost Carp', 
        'Grass Carp', 'Grayling', 'Gudgeon', 'Mirror Carp', 'Perch', 
        'Pike', 'Rainbow Trout', 'Roach', 'Rudd', 'Ruffe', 
        'Salmon', 'Tench', 'Trout', 'Zander'
    ]

    fishing_choices = [
        'Bait Fishing', 'Carp Fishing', 'Chod Fishing', 
        'Drop Shot Fishing', 'Feeder Fishing', 'Float Fishing',
        'Fly Fishing', 'Legering Fishing', 'Lure Fishing',
        'Pole Fishing', 'Pellet Waggler Fishing',
        'Predator Fishing', 'Spin Fishing',
        'Spod Fishing', 'Whip Fishing'
    ]

    for fish in fish_choices:
        TypeOfFish.objects.create(name=fish)
                
    for fishing in fishing_choices:
        TypeOfFishing.objects.create(name=fishing)

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),  # Keep this as 0001_initial
    ]
    
    operations = [
        migrations.RunPython(add_fish_and_fishing_types),
    ]