# Generated by Django 4.2.16 on 2024-12-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_slug'),
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourite_fish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.typeoffish'),
        ),
        migrations.AddField(
            model_name='blog',
            name='favourite_fishing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.typeoffishing'),
        ),
    ]
